//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregatedCounts) DeepCopyInto(out *AggregatedCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregatedCounts.
func (in *AggregatedCounts) DeepCopy() *AggregatedCounts {
	if in == nil {
		return nil
	}
	out := new(AggregatedCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockPageSpec) DeepCopyInto(out *BlockPageSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockPageSpec.
func (in *BlockPageSpec) DeepCopy() *BlockPageSpec {
	if in == nil {
		return nil
	}
	out := new(BlockPageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlocklistEntry) DeepCopyInto(out *BlocklistEntry) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlocklistEntry.
func (in *BlocklistEntry) DeepCopy() *BlocklistEntry {
	if in == nil {
		return nil
	}
	out := new(BlocklistEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CategoryEntry) DeepCopyInto(out *CategoryEntry) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CategoryEntry.
func (in *CategoryEntry) DeepCopy() *CategoryEntry {
	if in == nil {
		return nil
	}
	out := new(CategoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainEntry) DeepCopyInto(out *DomainEntry) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainEntry.
func (in *DomainEntry) DeepCopy() *DomainEntry {
	if in == nil {
		return nil
	}
	out := new(DomainEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListReference) DeepCopyInto(out *ListReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListReference.
func (in *ListReference) DeepCopy() *ListReference {
	if in == nil {
		return nil
	}
	out := new(ListReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsSpec) DeepCopyInto(out *LogsSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.LogClientsIPs != nil {
		in, out := &in.LogClientsIPs, &out.LogClientsIPs
		*out = new(bool)
		**out = **in
	}
	if in.LogDomains != nil {
		in, out := &in.LogDomains, &out.LogDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsSpec.
func (in *LogsSpec) DeepCopy() *LogsSpec {
	if in == nil {
		return nil
	}
	out := new(LogsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NativeEntry) DeepCopyInto(out *NativeEntry) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NativeEntry.
func (in *NativeEntry) DeepCopy() *NativeEntry {
	if in == nil {
		return nil
	}
	out := new(NativeEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSAllowlist) DeepCopyInto(out *NextDNSAllowlist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSAllowlist.
func (in *NextDNSAllowlist) DeepCopy() *NextDNSAllowlist {
	if in == nil {
		return nil
	}
	out := new(NextDNSAllowlist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextDNSAllowlist) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSAllowlistList) DeepCopyInto(out *NextDNSAllowlistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NextDNSAllowlist, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSAllowlistList.
func (in *NextDNSAllowlistList) DeepCopy() *NextDNSAllowlistList {
	if in == nil {
		return nil
	}
	out := new(NextDNSAllowlistList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextDNSAllowlistList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSAllowlistSpec) DeepCopyInto(out *NextDNSAllowlistSpec) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]DomainEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSAllowlistSpec.
func (in *NextDNSAllowlistSpec) DeepCopy() *NextDNSAllowlistSpec {
	if in == nil {
		return nil
	}
	out := new(NextDNSAllowlistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSAllowlistStatus) DeepCopyInto(out *NextDNSAllowlistStatus) {
	*out = *in
	if in.ProfileRefs != nil {
		in, out := &in.ProfileRefs, &out.ProfileRefs
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSAllowlistStatus.
func (in *NextDNSAllowlistStatus) DeepCopy() *NextDNSAllowlistStatus {
	if in == nil {
		return nil
	}
	out := new(NextDNSAllowlistStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSDenylist) DeepCopyInto(out *NextDNSDenylist) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSDenylist.
func (in *NextDNSDenylist) DeepCopy() *NextDNSDenylist {
	if in == nil {
		return nil
	}
	out := new(NextDNSDenylist)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextDNSDenylist) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSDenylistList) DeepCopyInto(out *NextDNSDenylistList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NextDNSDenylist, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSDenylistList.
func (in *NextDNSDenylistList) DeepCopy() *NextDNSDenylistList {
	if in == nil {
		return nil
	}
	out := new(NextDNSDenylistList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextDNSDenylistList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSDenylistSpec) DeepCopyInto(out *NextDNSDenylistSpec) {
	*out = *in
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]DomainEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSDenylistSpec.
func (in *NextDNSDenylistSpec) DeepCopy() *NextDNSDenylistSpec {
	if in == nil {
		return nil
	}
	out := new(NextDNSDenylistSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSDenylistStatus) DeepCopyInto(out *NextDNSDenylistStatus) {
	*out = *in
	if in.ProfileRefs != nil {
		in, out := &in.ProfileRefs, &out.ProfileRefs
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSDenylistStatus.
func (in *NextDNSDenylistStatus) DeepCopy() *NextDNSDenylistStatus {
	if in == nil {
		return nil
	}
	out := new(NextDNSDenylistStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSProfile) DeepCopyInto(out *NextDNSProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSProfile.
func (in *NextDNSProfile) DeepCopy() *NextDNSProfile {
	if in == nil {
		return nil
	}
	out := new(NextDNSProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextDNSProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSProfileList) DeepCopyInto(out *NextDNSProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NextDNSProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSProfileList.
func (in *NextDNSProfileList) DeepCopy() *NextDNSProfileList {
	if in == nil {
		return nil
	}
	out := new(NextDNSProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextDNSProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSProfileSpec) DeepCopyInto(out *NextDNSProfileSpec) {
	*out = *in
	out.CredentialsRef = in.CredentialsRef
	if in.AllowlistRefs != nil {
		in, out := &in.AllowlistRefs, &out.AllowlistRefs
		*out = make([]ListReference, len(*in))
		copy(*out, *in)
	}
	if in.DenylistRefs != nil {
		in, out := &in.DenylistRefs, &out.DenylistRefs
		*out = make([]ListReference, len(*in))
		copy(*out, *in)
	}
	if in.TLDListRefs != nil {
		in, out := &in.TLDListRefs, &out.TLDListRefs
		*out = make([]ListReference, len(*in))
		copy(*out, *in)
	}
	if in.Denylist != nil {
		in, out := &in.Denylist, &out.Denylist
		*out = make([]DomainEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Allowlist != nil {
		in, out := &in.Allowlist, &out.Allowlist
		*out = make([]DomainEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Privacy != nil {
		in, out := &in.Privacy, &out.Privacy
		*out = new(PrivacySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ParentalControl != nil {
		in, out := &in.ParentalControl, &out.ParentalControl
		*out = new(ParentalControlSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Rewrites != nil {
		in, out := &in.Rewrites, &out.Rewrites
		*out = make([]RewriteEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Settings != nil {
		in, out := &in.Settings, &out.Settings
		*out = new(SettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSProfileSpec.
func (in *NextDNSProfileSpec) DeepCopy() *NextDNSProfileSpec {
	if in == nil {
		return nil
	}
	out := new(NextDNSProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSProfileStatus) DeepCopyInto(out *NextDNSProfileStatus) {
	*out = *in
	if in.AggregatedCounts != nil {
		in, out := &in.AggregatedCounts, &out.AggregatedCounts
		*out = new(AggregatedCounts)
		**out = **in
	}
	if in.ReferencedResources != nil {
		in, out := &in.ReferencedResources, &out.ReferencedResources
		*out = new(ReferencedResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSProfileStatus.
func (in *NextDNSProfileStatus) DeepCopy() *NextDNSProfileStatus {
	if in == nil {
		return nil
	}
	out := new(NextDNSProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSTLDList) DeepCopyInto(out *NextDNSTLDList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSTLDList.
func (in *NextDNSTLDList) DeepCopy() *NextDNSTLDList {
	if in == nil {
		return nil
	}
	out := new(NextDNSTLDList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextDNSTLDList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSTLDListList) DeepCopyInto(out *NextDNSTLDListList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NextDNSTLDList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSTLDListList.
func (in *NextDNSTLDListList) DeepCopy() *NextDNSTLDListList {
	if in == nil {
		return nil
	}
	out := new(NextDNSTLDListList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NextDNSTLDListList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSTLDListSpec) DeepCopyInto(out *NextDNSTLDListSpec) {
	*out = *in
	if in.TLDs != nil {
		in, out := &in.TLDs, &out.TLDs
		*out = make([]TLDEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSTLDListSpec.
func (in *NextDNSTLDListSpec) DeepCopy() *NextDNSTLDListSpec {
	if in == nil {
		return nil
	}
	out := new(NextDNSTLDListSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NextDNSTLDListStatus) DeepCopyInto(out *NextDNSTLDListStatus) {
	*out = *in
	if in.ProfileRefs != nil {
		in, out := &in.ProfileRefs, &out.ProfileRefs
		*out = make([]ResourceReference, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NextDNSTLDListStatus.
func (in *NextDNSTLDListStatus) DeepCopy() *NextDNSTLDListStatus {
	if in == nil {
		return nil
	}
	out := new(NextDNSTLDListStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParentalControlSpec) DeepCopyInto(out *ParentalControlSpec) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]CategoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]ServiceEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SafeSearch != nil {
		in, out := &in.SafeSearch, &out.SafeSearch
		*out = new(bool)
		**out = **in
	}
	if in.YouTubeRestrictedMode != nil {
		in, out := &in.YouTubeRestrictedMode, &out.YouTubeRestrictedMode
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParentalControlSpec.
func (in *ParentalControlSpec) DeepCopy() *ParentalControlSpec {
	if in == nil {
		return nil
	}
	out := new(ParentalControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceSpec) DeepCopyInto(out *PerformanceSpec) {
	*out = *in
	if in.ECS != nil {
		in, out := &in.ECS, &out.ECS
		*out = new(bool)
		**out = **in
	}
	if in.CacheBoost != nil {
		in, out := &in.CacheBoost, &out.CacheBoost
		*out = new(bool)
		**out = **in
	}
	if in.CNAMEFlattening != nil {
		in, out := &in.CNAMEFlattening, &out.CNAMEFlattening
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceSpec.
func (in *PerformanceSpec) DeepCopy() *PerformanceSpec {
	if in == nil {
		return nil
	}
	out := new(PerformanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivacySpec) DeepCopyInto(out *PrivacySpec) {
	*out = *in
	if in.Blocklists != nil {
		in, out := &in.Blocklists, &out.Blocklists
		*out = make([]BlocklistEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Natives != nil {
		in, out := &in.Natives, &out.Natives
		*out = make([]NativeEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisguisedTrackers != nil {
		in, out := &in.DisguisedTrackers, &out.DisguisedTrackers
		*out = new(bool)
		**out = **in
	}
	if in.AllowAffiliate != nil {
		in, out := &in.AllowAffiliate, &out.AllowAffiliate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivacySpec.
func (in *PrivacySpec) DeepCopy() *PrivacySpec {
	if in == nil {
		return nil
	}
	out := new(PrivacySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencedResourceStatus) DeepCopyInto(out *ReferencedResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencedResourceStatus.
func (in *ReferencedResourceStatus) DeepCopy() *ReferencedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ReferencedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferencedResources) DeepCopyInto(out *ReferencedResources) {
	*out = *in
	if in.Allowlists != nil {
		in, out := &in.Allowlists, &out.Allowlists
		*out = make([]ReferencedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.Denylists != nil {
		in, out := &in.Denylists, &out.Denylists
		*out = make([]ReferencedResourceStatus, len(*in))
		copy(*out, *in)
	}
	if in.TLDLists != nil {
		in, out := &in.TLDLists, &out.TLDLists
		*out = make([]ReferencedResourceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReferencedResources.
func (in *ReferencedResources) DeepCopy() *ReferencedResources {
	if in == nil {
		return nil
	}
	out := new(ReferencedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceReference) DeepCopyInto(out *ResourceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceReference.
func (in *ResourceReference) DeepCopy() *ResourceReference {
	if in == nil {
		return nil
	}
	out := new(ResourceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RewriteEntry) DeepCopyInto(out *RewriteEntry) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RewriteEntry.
func (in *RewriteEntry) DeepCopy() *RewriteEntry {
	if in == nil {
		return nil
	}
	out := new(RewriteEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	if in.AIThreatDetection != nil {
		in, out := &in.AIThreatDetection, &out.AIThreatDetection
		*out = new(bool)
		**out = **in
	}
	if in.ThreatIntelligenceFeeds != nil {
		in, out := &in.ThreatIntelligenceFeeds, &out.ThreatIntelligenceFeeds
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.GoogleSafeBrowsing != nil {
		in, out := &in.GoogleSafeBrowsing, &out.GoogleSafeBrowsing
		*out = new(bool)
		**out = **in
	}
	if in.Cryptojacking != nil {
		in, out := &in.Cryptojacking, &out.Cryptojacking
		*out = new(bool)
		**out = **in
	}
	if in.DNSRebinding != nil {
		in, out := &in.DNSRebinding, &out.DNSRebinding
		*out = new(bool)
		**out = **in
	}
	if in.IDNHomographs != nil {
		in, out := &in.IDNHomographs, &out.IDNHomographs
		*out = new(bool)
		**out = **in
	}
	if in.Typosquatting != nil {
		in, out := &in.Typosquatting, &out.Typosquatting
		*out = new(bool)
		**out = **in
	}
	if in.DGA != nil {
		in, out := &in.DGA, &out.DGA
		*out = new(bool)
		**out = **in
	}
	if in.NRD != nil {
		in, out := &in.NRD, &out.NRD
		*out = new(bool)
		**out = **in
	}
	if in.DDNS != nil {
		in, out := &in.DDNS, &out.DDNS
		*out = new(bool)
		**out = **in
	}
	if in.Parking != nil {
		in, out := &in.Parking, &out.Parking
		*out = new(bool)
		**out = **in
	}
	if in.CSAM != nil {
		in, out := &in.CSAM, &out.CSAM
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySpec.
func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEntry) DeepCopyInto(out *ServiceEntry) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEntry.
func (in *ServiceEntry) DeepCopy() *ServiceEntry {
	if in == nil {
		return nil
	}
	out := new(ServiceEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingsSpec) DeepCopyInto(out *SettingsSpec) {
	*out = *in
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(LogsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockPage != nil {
		in, out := &in.BlockPage, &out.BlockPage
		*out = new(BlockPageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Performance != nil {
		in, out := &in.Performance, &out.Performance
		*out = new(PerformanceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Web3 != nil {
		in, out := &in.Web3, &out.Web3
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingsSpec.
func (in *SettingsSpec) DeepCopy() *SettingsSpec {
	if in == nil {
		return nil
	}
	out := new(SettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLDEntry) DeepCopyInto(out *TLDEntry) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLDEntry.
func (in *TLDEntry) DeepCopy() *TLDEntry {
	if in == nil {
		return nil
	}
	out := new(TLDEntry)
	in.DeepCopyInto(out)
	return out
}
